USE INTECEDUCONTINUA;
GO

IF OBJECT_ID('dbo.TEAMS_ADMINISTRADOR_ADICIONAL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TEAMS_ADMINISTRADOR_ADICIONAL(
        id int IDENTITY(1,1) NOT NULL CONSTRAINT PK_TEAMS_ADMINISTRADOR_ADICIONAL PRIMARY KEY,
        team_id nvarchar(120) NOT NULL,
        team_display_name nvarchar(255) NULL,
        graph_user_id nvarchar(120) NOT NULL,
        display_name nvarchar(255) NULL,
        mail nvarchar(255) NULL,
        user_principal_name nvarchar(255) NULL,
        rol nvarchar(50) NOT NULL CONSTRAINT DF_TEAMS_ADMINISTRADOR_ADICIONAL_ROL DEFAULT('owner'),
        activo bit NOT NULL CONSTRAINT DF_TEAMS_ADMINISTRADOR_ADICIONAL_ACTIVO DEFAULT(1),
        creado_en datetime2 NOT NULL CONSTRAINT DF_TEAMS_ADMINISTRADOR_ADICIONAL_CREADO DEFAULT(SYSDATETIME()),
        actualizado_en datetime2 NOT NULL CONSTRAINT DF_TEAMS_ADMINISTRADOR_ADICIONAL_ACTUALIZADO DEFAULT(SYSDATETIME())
    );
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UX_TEAMS_ADMINISTRADOR_ADICIONAL_TEAM_USER'
      AND object_id = OBJECT_ID('dbo.TEAMS_ADMINISTRADOR_ADICIONAL')
)
BEGIN
    CREATE UNIQUE INDEX UX_TEAMS_ADMINISTRADOR_ADICIONAL_TEAM_USER
        ON dbo.TEAMS_ADMINISTRADOR_ADICIONAL(team_id, graph_user_id);
END;
GO
