USE INTECEDUCONTINUA;
GO

IF OBJECT_ID('dbo.TEAMS_ADMINISTRADOR_ADICIONAL', 'U') IS NOT NULL
   AND COL_LENGTH('dbo.TEAMS_ADMINISTRADOR_ADICIONAL', 'team_display_name') < 512
BEGIN
    ALTER TABLE dbo.TEAMS_ADMINISTRADOR_ADICIONAL
        ALTER COLUMN team_display_name nvarchar(256) NULL;
END;
GO
